staratlasmeta/factory

src/factions.ts

Export interfaces.
Update verbiage in functions to be more clear.

FIX: Exporting interfaces from factory.

---

src/score.ts
src/util/scoreHelpers.ts
src/util/scoreIdl.ts

Cu 1qnqtg1 score harvest settle

---

src/score.ts
src/util/scoreIdl.ts

FEAT: updated initialize to handle resource registration

---

src/score.ts
src/util/scoreHelpers.ts
src/util/scoreIdl.ts

Cu-1rxky8m: Close accounts

---

src/score.ts
src/util/scoreIdl.ts

Update accounts and IDL to match clock/memo updates to score program.

Clock account hotfix

---

src/score.ts
src/util/scoreIdl.ts

FEAT: create partial deposit instruction

---

src/score.ts
src/util/scoreIdl.ts

FEAT: added tokenOwnerAccount for permissionless resource refill

---

src/score.ts
src/util/scoreIdl.ts

FEAT: update reward rate instruction

---

src/score.ts
src/util/scoreIdl.ts

FEAT: deregister ship instruction

---

src/score.ts
src/util/scoreIdl.ts

FEAT: updated IDL for u32 + millis

---

src/score.ts
src/util/scoreIdl.ts

FIX: IDL for updated close accounts + missing stakedTimePaid

---

src/score.ts
src/util/scoreIdl.ts

FIX: updated idl for only one update auth

---

package.json
src/score.ts
src/util/scoreLogIdl.ts

Merge into main

---

package-lock.json
src/marketplace/pda_getters/pda_getters.ts
src/marketplace/types/marketplace_accounts.ts

- Add getter function which returns an object containing
the registered currencies' mint addresses and associated
market royalty rates

Add getter for all registered currencies

---

src/marketplace/types/gmLogsIdl.ts
src/marketplace/types/marketplace_accounts.ts
src/marketplace/utils/getMarketplaceProgram.ts

Add enum for memos and gmLogsIdl getter fn

---

package-lock.json
src/marketplace/pda_getters/pda_getters.ts
src/marketplace/types/gmIdl.ts

- Updates PDA and data size filters for registered currencies

fix: update idl and pda getters for new currency data size

---

src/marketplace/models/Order.ts
src/marketplace/services/GmClientService.ts
src/marketplace/services/GmEventService.ts
src/marketplace/services/GmOrderbookService.ts
src/marketplace/services/OrderCacheService.ts

- Adds ws listener cleanup to `GmEventService`
- Replaces `Anchor.Wallet` integration in `GmEventService` with null
- Adds `slotContext` to `Order` class
- Uses `slotContext` to prevent potential state management issues with the `GmOrderbookService`

fix: add better ws cleanup to GmEventService

---

package-lock.json
package.json
src/marketplace/instruction_builders/exchangeOrder.ts
src/marketplace/models/Order.ts
src/marketplace/services/GmClientService.ts
src/marketplace/services/GmEventService.ts
src/marketplace/services/GmOrderbookService.ts

- Refactor `Order.price` to be a `BN`
- Add `Order.uiPrice` field

fix: refactor Order class to use BN for price info

---

src/marketplace/services/GmClientService.ts

- Adds `getBnPriceForCurrency` method

feat: add convenience method for converting to bn for currency

---

src/marketplace/services/GmClientService.ts
src/marketplace/utils/gmHelper.test.ts
src/marketplace/utils/gmHelper.ts

fix(bug): The previous code inadvertently converted the number to an INT by doing new BN(uiPrice) before multiplying the uiPrice into the correct number of digits:
e.g. if uiPrice = 7.16 then new BN(uiPrice) would become 700000. Basically, we have to do the Number Multiplication before converting to BN

fix(marketplace): Bug where percision is lost on creating order

---

.gitignore
package-lock.json
package.json
src/score.ts

- All withdraw related functions use `GetTokenAccount` rather than just using a user's ATA
- Change return type of all withdraw related functions from `TransactionInstruction[]` to `FactoryReturn`
- Remove token account params from all withdraw related functions

Cu 3ajjnj4 score token account getters

---

package-lock.json
src/marketplace/instruction_builders/cancelOrder.ts
src/marketplace/instruction_builders/exchangeOrder.ts
src/marketplace/pda_getters/pda_info_getters.ts
src/marketplace/services/GmClientService.ts
src/marketplace/types/gmIdl.ts
src/marketplace/types/marketplace_accounts.ts

- Cancel takes an optional payer parameter which allows authority
wallet to sign/pay for cancel tx. Defaults to order initializer if not
provided
- Exchange temporarily takes optional params for staking program

fix(GM) - Make API changes non-breaking

---

src/marketplace/instruction_builders/exchangeOrder.ts

- Only generate random keys if staking related accounts
are not provided

Allow passing of staking accounts into exchange function

---

src/atlas-staking/instruction_builders/index.ts
src/atlas-staking/instruction_builders/updateCooldownPeriod.ts
src/atlas-staking/types/stakingIdl.ts

Add instruction for update cooldown period

---

src/atlas-staking/pda_getters/index.ts
src/atlas-staking/pda_getters/pda_getters.ts
src/atlas-staking/types/stakingIdl.ts
src/atlas-staking/types/stakingProgramAccounts.ts

- Add getter fn for all staking accounts of registered stake
- export seeds for staking program
- update IDL

Store registered stake in staking account

---

src/atlas-staking/pda_getters/index.ts
src/atlas-staking/pda_getters/pda_getters.ts
src/atlas-staking/types/stakingIdl.ts
src/atlas-staking/types/stakingProgramAccounts.ts
src/marketplace/types/gmLogsIdl.ts

Staking memos

---

package-lock.json
package.json
src/marketplace/instruction_builders/updateCurrency.ts
src/marketplace/services/GmEventService.ts

fix: correctly bind currency update methods

---

package-lock.json
src/marketplace/instruction_builders/exchangeOrder.ts
src/marketplace/instruction_builders/feeExempt.ts
src/marketplace/instruction_builders/index.ts
src/marketplace/pda_getters/pda_getters.ts
src/marketplace/pda_getters/pda_info_getters.ts
src/marketplace/pda_getters/seeds.ts
src/marketplace/services/GmClientService.ts
src/marketplace/types/gmIdl.ts
src/marketplace/types/marketplace_accounts.ts

Fee exempt

---

src/atlas-staking/instruction_builders/harvestRewards.ts
src/atlas-staking/instruction_builders/unstakeTokens.ts
src/atlas-staking/instruction_builders/withdrawTokens.ts
src/marketplace/instruction_builders/cancelOrder.ts
src/marketplace/instruction_builders/createOrder.ts
src/marketplace/instruction_builders/exchangeOrder.ts
src/score.ts
src/util/helpers.ts

- Add system program create account instruction if token account is missing
- getTokenAccount returns array of instructions
- Update factory instruction builders to push array of instructions received from getTokenAccount

Create token account before initializing

---

src/marketplace/pda_getters/pda_getters.ts
src/marketplace/services/GmClientService.ts
src/marketplace/services/constants.ts
src/marketplace/types/marketplace_accounts.ts
src/marketplace/types/services.ts

Add getter for all fee exemption accounts

---

src/factions.ts
src/marketplace/pda_getters/pda_info_getters.ts

chore: fix linter

---

README.md

fix: reformat readme

---

.github/workflows/release.yml
README.md
package.json

fix: release-test

---

package.json

fix: version-bump

---

.github/workflows/release.yml

fix: add GITHUB_TOKEN
